# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DriverApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DriverApp

  pod 'AppAuth', '>=0.94'

  target 'DriverAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DriverApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DriverApp-tvOS

  target 'DriverApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
